FROM python:3.12-slim-bullseye

## Install dependencies (curl)
RUN apt-get -y update; apt-get -y install curl git

# Create a non-root-user group
RUN groupadd -r appgroup && useradd -r -g appgroup appuser

## No shell entrypoint for root
RUN chsh -s /usr/sbin/nologin root

## Install gunicorn
RUN pip install --upgrade gunicorn poetry

## Set the user to non-root
# USER appuser

WORKDIR /app

## Create a bin dir for app installations and add to path
RUN mkdir -p /app/bin
ENV PATH="/app/bin:${PATH}"

## Open into the volume mount
WORKDIR /mnt/sparrow

## Open in bash
CMD ["/bin/bash"] 